repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files
    -   id: detect-aws-credentials
    -   id: spell-checker
        args: ['--ignore-acronyms']
    -   id: import-sorter
        args: ['--single-quotes']

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.900
    hooks:
    -   id: mypy
